export const PricingData = [
  {
    id: 1,
    name: "1 BHK",
    price: "15,000/-",
    kitName: "1 BHK Basic Kit",
    kit: "Basic Kit",
    list: [
      "Living Room 3 Lights, 1 Fan, AC, TV, DTH and DVD",
      "Bedroom 1 Light and 1 Fan",
      "Works With Alexa & Google Assistant",
      "Lifetime Free Mobile application Android/IOS",
      "Free Installation at your Convenient time",
      "2 Years Replacement Warranty and Lifetime Technical Support",
    ],
  },
  {
    id: 2,
    name: "2 BHK",
    price: "23,000/-",
    kitName: "2 BHK Basic Kit",
    kit: "Basic Kit",
    list: [
      "Living Room 3 Lights, 1 Fan, AC, TV, DTH and DVD Temperature Sensor, Light Sensor and Humidity Sensor",
      "Bedroom 01 Light and 1 Fan",
      "Bedroom 02 Light and 1 Fan",
      "16 A 1 No Geyser Control",
      "Works With Alexa & Google Assistant",
      "Lifetime Free Mobile application Android/IOS",
      "Free Installation at your Convenient time",
      "2 Years Replacement Warranty and Lifetime Technical Support",
    ],
  },
  {
    id: 3,
    name: "3 BHK",
    price: "28,000/-",
    kitName: "3 BHK Basic Kit",
    kit: "Basic Kit",
    list: [
      "Living Room 4 Lights, 1 Fan, AC, TV, DTH and DVD Temperature Sensor, Light Sensor and Humidity Sensor.",
      "Bedroom 01 Light and 1 Fan",
      "Bedroom 02 Light and 1 Fan",
      "Bedroom 03 Light and 1 Fan",
      "16 A 1 No Geyser Control",
      "Works With Alexa & Google Assistant",
      "Lifetime Free Mobile application Android/IOS",
      "Free Installation at your Convenient time",
      "2 Years Replacement Warranty and Lifetime Technical Support",
    ],
  },
];
